---
title: "Prueba_importaciondatos"
author: "Mar Riveiro Cabado"
date: "2023-11-02"
output: html_document
---


```{r}
library(dplyr)
library(tidyr)
library(readr)
```


```{r}
estaciones <- read_delim("data/Maestro_Climatologico_2022.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE,show_col_types = FALSE)
```


```{r}
ruta_carpeta<-"data/Variables/2022"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")
class(archivos_climaticos)
archivos_climaticos
```
```{r}
#en este chunck cargamos el dataset más pequeño que nos sirve de referencia para cortar los otros
#ES NECESARIO CARGAR AL MENOS EL DATASET MÁS PEQUEÑO PARA OBTENER SU LONGITUD

W_MED_2022 <- read_delim("data/Variables/W_MED_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,show_col_types = FALSE)

mantener_filas_por_nombre <- function(df, nombres) {
  return(df[df$Indicativo %in% nombres, ])
}

#tomamos el vector de nombres indicativos
Indicativos<- (c(W_MED_2022[["Indicativo"]]))
length(Indicativos)

```

```{r}
#EL DATAFRAME CON LOS INDICATIVOS DE TODOS LOS DATASETS QUE LO CONFORMAN
datos<-(mantener_filas_por_nombre(datos, nombres = Indicativos))
```

```{r}

datos<-data.frame(Indicativo=estaciones$INDICATIVO)

mantener_filas_por_nombre <- function(df, nombres) {
  return(df[df$Indicativo %in% nombres, ])
}

datos_2022<-data.frame(Indicativo=estaciones$INDICATIVO)
lista22<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista22[[ruta_completa_archivo]]<- variable
    prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_") #renombra las columnas del dataframe quitando la primera columna ("Indicativo") y le añade el prefijo definido arriba.
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2022<-merge(datos_2022,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)

}
indice_menor_filas <- which.min(sapply(lista22, nrow))
dataframe_menor_filas <- lista22[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2022<-(mantener_filas_por_nombre(datos_2022, nombres = Indicativos))

```


```{r}
ruta_carpeta<-"data/Variables/2021"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2021<-data.frame(Indicativo=estaciones$INDICATIVO)
lista21<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista21[[ruta_completa_archivo]]<- variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2021<-merge(datos_2021,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}
indice_menor_filas <- which.min(sapply(lista21, nrow))
dataframe_menor_filas <- lista21[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2021<-(mantener_filas_por_nombre(datos_2021, nombres = Indicativos))
```

```{r}
ruta_carpeta<-"data/Variables/2020"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2020<-data.frame(Indicativo=estaciones$INDICATIVO)
lista20<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista20[[ruta_completa_archivo]]<- variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2020<-merge(datos_2020,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}

indice_menor_filas <- which.min(sapply(lista20, nrow))
dataframe_menor_filas <- lista20[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2020<-(mantener_filas_por_nombre(datos_2020, nombres = Indicativos))
```

```{r}
ruta_carpeta<-"data/Variables/2019"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2019<-data.frame(Indicativo=estaciones$INDICATIVO)
lista19<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista19[[ruta_completa_archivo]] <- variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2019<-merge(datos_2019,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}
indice_menor_filas <- which.min(sapply(lista19, nrow))
dataframe_menor_filas <- lista19[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2019<-(mantener_filas_por_nombre(datos_2019, nombres = Indicativos))
```

```{r}
ruta_carpeta<-"data/Variables/2018"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2018<-data.frame(Indicativo=estaciones$INDICATIVO)
lista18<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista18[[ruta_completa_archivo]]<-variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2018<-merge(datos_2018,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}
indice_menor_filas <- which.min(sapply(lista18, nrow))
dataframe_menor_filas <- lista18[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2018<-(mantener_filas_por_nombre(datos_2018, nombres = Indicativos))
```

```{r}
ruta_carpeta<-"data/Variables/2017"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2017<-data.frame(Indicativo=estaciones$INDICATIVO)
lista17<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista17[[ruta_completa_archivo]]<-variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2017<-merge(datos_2017,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}
indice_menor_filas <- which.min(sapply(lista17, nrow))
dataframe_menor_filas <- lista17[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2017<-(mantener_filas_por_nombre(datos_2017, nombres = Indicativos))
```

```{r}
ruta_carpeta<-"data/Variables/2016"
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

datos_2016<-data.frame(Indicativo=estaciones$INDICATIVO)
lista16<-list()
for (archivo in archivos_climaticos) {
  
    ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
    
    variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE, trim_ws=TRUE, show_col_types=FALSE)
    lista16[[ruta_completa_archivo]]<-variable
  prefijo <- substr(archivo, 1, 2)
  
  colnames(variable)[-1] <- paste(prefijo, colnames(variable)[-1], sep = "_")
    
  #colnames(variable)[-1] <- paste("p_", colnames(variable)[-1], sep = "")
  datos_variable<-as.data.frame(variable) 
  datos_2016<-merge(datos_2016,datos_variable, by="Indicativo", sort=FALSE,all.x = TRUE, all.y = TRUE)
}
indice_menor_filas <- which.min(sapply(lista16, nrow))
dataframe_menor_filas <- lista16[[indice_menor_filas]]
Indicativos<- (c(dataframe_menor_filas[["Indicativo"]]))
length(Indicativos)
datos_2016<-(mantener_filas_por_nombre(datos_2016, nombres = Indicativos))
```

