---
title: "ProyectoAED"
author: "Alex Riera Merino"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(dplyr)
```


```{r}
estaciones<-read_delim("./data/Maestro_Climatologico_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,show_col_types = FALSE)
```

```{r}
#proceso para la extración de datasets de 1 único año.

dataset1 <- read_delim("./data/Variables/2022/HR_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
dataset2 <- read_delim("./data/Maestro_Climatologico_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ruta_carpeta<-"./data/Variables/2022"

archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")

nuevo_dataset <- dataset1 %>%
   pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_HR")

dataset3 <- read_delim("./data/Variables/2022/INSO_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_2 <- dataset3 %>%
  pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_IN")
nuevo_dataset_2 <- nuevo_dataset_2[1:nrow(nuevo_dataset),]


dataset_final <- left_join(nuevo_dataset,nuevo_dataset_2)


 
dataset4 <- read_delim("./data/Variables/2022/P_MES_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_3 <- dataset4 %>%
  pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_PMES") 

nuevo_dataset_3 <- nuevo_dataset_3[1:nrow(nuevo_dataset),]

dataset_final <- left_join(dataset_final,nuevo_dataset_3)

dataset5 <- read_delim("./data/Variables/2022/TM_MAX_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_4 <- dataset5 %>%
   pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_TMAX")

nuevo_dataset_4 <- nuevo_dataset_4[1:nrow(nuevo_dataset),]

dataset_final <- left_join(dataset_final,nuevo_dataset_4)

dataset6 <- read_delim("./data/Variables/2022/TM_MES_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_5 <- dataset6 %>%
   pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_TMES")

nuevo_dataset_5 <- nuevo_dataset_5[1:nrow(nuevo_dataset),]

dataset_final <- left_join(dataset_final,nuevo_dataset_5)
 
dataset7 <- read_delim("./data/Variables/2022/TM_MIN_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_6 <- dataset7 %>%
   pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_TMIN")

nuevo_dataset_6 <- nuevo_dataset_6[1:nrow(nuevo_dataset),]

dataset_final <- left_join(dataset_final,nuevo_dataset_6)
 
dataset8 <- read_delim("./data/Variables/2022/W_MED_2022.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)
nuevo_dataset_7 <- dataset8 %>%
   pivot_longer(col = -c(Indicativo), names_to = "Meses", values_to = "Valores_WM")

nuevo_dataset_7 <- nuevo_dataset_7[1:nrow(nuevo_dataset),]

dataset_final <- left_join(dataset_final,nuevo_dataset_7)

```


```{r}
carpeta_base<-"./data/Variables/"

años<-2016:2022

lista_dataframes <- list()

for (año in años){
  
ruta_carpeta<-file.path(carpeta_base, as.character(año))
archivos_climaticos <- list.files(ruta_carpeta,pattern = ".*.csv")


df_año<-data.frame(Indicativo = character(0), Meses = character(0), Valores= numeric(0))


for (archivo in archivos_climaticos) {
  
  ruta_completa_archivo<-file.path(ruta_carpeta,archivo)
  variable <-read_delim(ruta_completa_archivo, delim = ";", escape_double = FALSE,
                          trim_ws=TRUE, show_col_types=FALSE)
  prefijo <- substr(archivo, 1, nchar(archivo) - 9)

  df_variable <- variable %>%
      pivot_longer(col = -c(Indicativo), names_to = "Meses", 
                   values_to = prefijo) 
  
    if (archivo == archivos_climaticos[1]) {
        
      df_año <- df_variable
      
     } else {
       
      df_año <- left_join(df_año,df_variable, by=join_by("Indicativo","Meses"))
     }
  
}
  lista_dataframes[[as.character(año)]] <- df_año
  assign(paste0("df_", año), df_año, envir = .GlobalEnv)
  carpeta<-"./data/"
  nombre_archivo <- file.path(carpeta, paste0("dataset_",año,".csv"))
  write.csv(df_año, nombre_archivo, row.names = FALSE)
}

rm(df_variable,variable,df_año)
```

HR -> humedad relativa mensual/anual (%)
INSO -> Media mensual/anual de la insolación diaria (horas)
P_MES -> Precipitación total mensual/anual (mm)
TM_MAX -> Temperatura media mensual/anual de las máximas (°C)
TM_MES -> Temperatura media mensual/anual (°C)
TM_MIN -> Temperatura media mensual/anual de las mínimas (°C)

```{r}
library(mice)

df_2016
faltan_2016<- colMeans(is.na(df_2016)) * 100
faltan_2016

data_filtered <- df_2016 %>% filter(Meses != "anual") #filtro el dataset quitando los años

imputed_data_filtered <- mice(data_filtered, m = 50, method = "pmm") #hago la imputación de datos con mice mediante el metodo de predictive mean matching

imputed_data <- complete(imputed_data_filtered, action = 1) #introduzco los datos

filtered_rows <- df_2016 %>% filter(Meses == "anual") #tomo el dataset que solo contiene los "anual"

#ahora obtengo los valores anuales por indicativo para cada variable
columnas <- c("HR", "INSO","TM_MAX","TM_MES","TM_MIN","W_MED")
columnas2 <- c("P_MES")
columnas_F <- c("HR", "INSO","P_MES","TM_MAX","TM_MES","TM_MIN","W_MED")

#dataframe con los promedios anuales por indicativo
result <- imputed_data %>%
  group_by(Indicativo) %>%
  summarise(across(all_of(columnas), mean))

#dataframe con la suma anual de precipitaciones
result2 <-imputed_data %>%
  group_by(Indicativo)%>%
  summarise(across(all_of("P_MES"), sum))

#los uno y los ordeno conforme al original

df_2016_anual <- mutate(result, result2)
df_2016_anual <-df_2016_anual[,c("Indicativo","HR", "INSO","P_MES","TM_MAX","TM_MES","TM_MIN","W_MED")]



```

```{r}

library(ggplot2)
library(gganimate)
factorizar_meses <- function(df) {
  df$Meses <- factor(df$Meses, levels = c("enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"))
  return(df)
}

nombres_dataframes <- c("df_mensual2016", "df_mensual2017", "df_mensual2018", "df_mensual2019", "df_mensual2020", "df_mensual2021", "df_mensual2022")

# Bucle for para factorizar la columna Meses en cada dataframe
for (nombre_df in nombres_dataframes) {
  # Obtener el dataframe por nombre
  df <- get(nombre_df)
  
  # Factorizar la columna Meses utilizando la función
  df_factorizado <- factorizar_meses(df)
  
  # Asignar el dataframe factorizado de vuelta al entorno global
  assign(nombre_df, df_factorizado)
}



# ggplot(grupo, aes(x = grupo$Meses, y = grupo$P_MES , fill = grupo$Indicativo)) +
#   geom_bar(stat = "identity") +
#   labs(x = "Mes", y = "Promedio de Valor", title = "Precipitaciones") + theme(axis.text.x = element_text(angle = 90, hjust = 1))+
#   theme_minimal()

#Para el calculo de outliers se hizo uso de la regla MADM
#outliers <- which(abs(grupo$W_MED- median(grupo$W_MED)) > 3*mad(grupo$W_MED))



list2env(dataframes_anuales, envir = .GlobalEnv)
list2env(dataframes_mensuales, envir = .GlobalEnv)

lista_outliers <- list()

for (df_names in names(dataframes_mensuales)) {
  df <- dataframes_mensuales[[df_names]]
  outliers_df <- list()
  for (i in names(df)) {
    outliers <- NULL
  if (is.numeric(df[[i]])) {
    iqr <- IQR(df[[i]])
    inferior <- quantile(df[[i]])[2]
    superior <- quantile(df[[i]])[4]
    outliers <- df[df[[i]] < inferior | df[[i]] > superior, ]
    outliers_df[[i]] <- outliers
  }
  
  cat("Variable:", i, "\t Outliers:", nrow(outliers), "\n")
  }
  
  lista_outliers[[df_names]] <- outliers_df
}
#variables que queremos representar


grafico_prueba_outliers <- df_mensual2017 %>%
  ggplot(aes(x = PROVINCIA , y = P_MES)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))




# grafico_animado <- df_mensual2017 %>%
#   ggplot(aes(x = Meses, y = P_MES)) + 
#   geom_boxplot() +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#   labs(title = "Grafica animada Precipitaciones", xlab("Meses"), ylab("Precipitaciones"))
# grafico_animado
# 
# animacion_2 <- grafico_animado + transition_states(P_MES, transition_length = 1, state_length = 0.5)
# anim_save("animacion2.gif", animation = animacion_2, renderer = gifski_renderer())




# Supongamos que tienes un dataframe llamado 'datos' con columnas 'Provincia', 'Año' y 'Precipitaciones'

#Crea una gráfica ggplot básica

p <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = P_MES, group = Meses)) +
  geom_line() +
  labs(title = 'Precipitaciones por Provincia', x = 'Provincia', y = 'Precipitaciones') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
p_animada <- p + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("p_animada.gif", animation = p_animada, renderer = gifski_renderer())

browseURL("p_animada.gif")

tmes <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = TM_MES, group = Meses)) +
  geom_line() +
  labs(title = 'Temperatura Media por Provincia', x = 'Provincia', y = 'Temperatura Media') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
TMes_animada <- tmes + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("TMes_animada.gif", animation = TMes_animada, renderer = gifski_renderer())

browseURL("TMes_animada.gif")


tmmin <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = TM_MIN, group = Meses)) +
  geom_line() +
  labs(title = 'Temperatura Media Minima por Provincia', x = 'Provincia', y = 'Temperatura Media Minima') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
TMmin_animada <- tmmin + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("TMmin_animada.gif", animation = TMmin_animada, renderer = gifski_renderer())

browseURL("TMmin_animada.gif")

tmmax <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = TM_MAX, group = Meses)) +
  geom_line() +
  labs(title = 'Temperatura Media Máxima por Provincia', x = 'Provincia', y = 'Temperatura Media Máxima') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
TMmax_animada <- tmmax + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("TMmax_animada.gif", animation = TMmax_animada, renderer = gifski_renderer())

browseURL("TMmax_animada.gif")

hr <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = HR, group = Meses)) +
  geom_line() +
  labs(title = 'Humedad Relativa por Provincia', x = 'Provincia', y = 'Humedad Relativa') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
HR_animada <- hr + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("HR_animada.gif", animation = HR_animada, renderer = gifski_renderer())

browseURL("HR_animada.gif")


inso <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = INSO, group = Meses)) +
  geom_line() +
  labs(title = 'Insolación por Provincia', x = 'Provincia', y = 'Insolación') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
INSO_animada <- inso + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("INSO_animada.gif", animation = INSO_animada, renderer = gifski_renderer())

browseURL("INSO_animada.gif")


wm <- ggplot(df_mensual2017, aes(x = PROVINCIA, y = W_MED, group = Meses)) +
  geom_line() +
  labs(title = 'Viento Medio por Provincia', x = 'Provincia', y = 'Viento Medio') +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#transition_reveal(P_MES)
# Añade la animación por año
WM_animada <- wm + transition_states(Meses, transition_length = 2, state_length = 1)
anim_save("WM_animada.gif", animation = WM_animada, renderer = gifski_renderer())

browseURL("WM_animada.gif")


```


```{r}


dataset_anual_2 <- data.frame(df_anual2017$P_MES, df_anual2018$P_MES)
dataset_anual_3 <- data.frame(dataset_anual_2, df_anual2019$P_MES)
dataset_anual_4 <- data.frame(dataset_anual_3, df_anual2020$P_MES)
dataset_anual_5 <- data.frame(dataset_anual_4, df_anual2021$P_MES)
dataset_anual_precipitaciones <- data.frame(dataset_anual_5, df_anual2022$P_MES)
names(dataset_anual_precipitaciones) <- c("2017","2018","2019","2020","2021","2022")



datos_largo <- gather(dataset_anual_precipitaciones, key = "año", value = "precipitacion")


grafica1 <- ggplot(datos_largo, aes(x = precipitacion, y = año,  color = año)) +
  geom_line() +
  coord_flip() +
  scale_x_continuous(limits = c(0,550)) +
  labs(title = "Distribución de Precipitaciones por Año",
       x = "Precipitacion",  # Elimina la etiqueta del eje x
       y = "Año") +
  theme_minimal() +
  theme(axis.text.y  = element_text(angle = 90, hjust = 1))


grafica1

grafica_animada1 <- grafica1 + transition_reveal(precipitacion)
grafica_animada1
anim_save("grafica_animada1", animation = grafica_animada1, renderer = gifski_renderer())
browseURL("grafica_animada1.gif")



dataset_anual_2.1 <- data.frame(df_anual2017$TM_MES, df_anual2018$TM_MES)
dataset_anual_3.1 <- data.frame(dataset_anual_2.1, df_anual2019$TM_MES)
dataset_anual_4.1 <- data.frame(dataset_anual_3.1, df_anual2020$TM_MES)
dataset_anual_5.1 <- data.frame(dataset_anual_4.1, df_anual2021$TM_MES)
dataset_anual_temperaturas <- data.frame(dataset_anual_5.1, df_anual2022$TM_MES)
names(dataset_anual_temperaturas) <- c("2017","2018","2019","2020","2021","2022")

datos_largo.1 <- gather(dataset_anual_temperaturas, key = "año", value = "temperatura")



grafica2 <- ggplot(datos_largo.1, aes(x = temperatura, y = año, color = año)) +
  geom_line() +
  coord_flip() +
  scale_x_continuous(limits = c(0,35)) +
  labs(title = "Distribución de Temperatura por Año",
       xlab = "Años",
       ylab = "Temperatura") +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 90, hjust = 1))

grafica2

grafica_animada2 <- grafica2 + transition_reveal(temperatura)
grafica_animada2
anim_save("grafica_animada2.gif", animation = grafica_animada2, renderer = gifski_renderer())
browseURL("grafica_animada2.gif")

dataset_anual_2.2 <- data.frame(df_anual2017$INSO, df_anual2018$INSO)
dataset_anual_3.2 <- data.frame(dataset_anual_2.2, df_anual2019$INSO)
dataset_anual_4.2 <- data.frame(dataset_anual_3.2, df_anual2020$INSO)
dataset_anual_5.2 <- data.frame(dataset_anual_4.2, df_anual2021$INSO)
dataset_anual_inso <- data.frame(dataset_anual_5.2, df_anual2022$INSO)
names(dataset_anual_inso) <- c("2017","2018","2019","2020","2021","2022")

datos_largo.2 <- gather(dataset_anual_inso, key = "año", value = "insolacion")

grafica3 <- ggplot(datos_largo.2, aes(x = insolacion, y = año, color = año)) +
  geom_line() +
  coord_flip() +
  scale_x_continuous(limits = c(0,20)) +
  labs(title = "Distribución de Insolacion por Año",
       xlab = "Años",
       ylab = "Insolacion") +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 90, hjust = 1))

grafica3

grafica_animada3 <- grafica3 + transition_reveal(insolacion)
grafica_animada3
anim_save("grafica_animada3.gif", animation = grafica_animada3, renderer = gifski_renderer())
browseURL("grafica_animada3.gif")

```



